name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        ndk-version: 25.1.8937393

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon --stacktrace

    - name: Build Release AAB (Android App Bundle)
      run: ./gradlew bundleRelease --no-daemon --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk-${{ github.ref_name || github.event.inputs.version }}
        path: app/build/outputs/apk/release/*.apk

    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: release-aab-${{ github.ref_name || github.event.inputs.version }}
        path: app/build/outputs/bundle/release/*.aab

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: LeafLogic ${{ github.ref }}
        body: |
          ## LeafLogic - LLM-Powered Health & Food Tracking App
          
          ### 🚀 What's New
          - Complete Android health and food tracking application
          - LLM-powered nutrition assistant with intelligent recommendations
          - Enterprise-grade security with database encryption and biometric authentication
          - Modern Material Design 3 UI following latest Android standards
          - Real-time food tracking with nutritional analysis
          - Health metrics tracking with progress visualization
          
          ### 📱 Installation
          1. Download the APK file from the release assets
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK file
          4. Launch LeafLogic and start tracking your health journey!
          
          ### 🔒 Security Features
          - SQLCipher database encryption for sensitive health data
          - Biometric authentication (fingerprint/face recognition)
          - Photo-enhanced encryption key generation
          - Privacy by design with local data processing
          
          ### 📋 Requirements
          - Android 7.0 (API level 24) or higher
          - Biometric hardware for enhanced security features
          - Internet connection for LLM nutrition assistance
        draft: false
        prerelease: false